include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    todo: info
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false

linter:
  rules:
    # From https://github.com/flutter/samples/blob/master/gallery/analysis_options.yaml
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - non_constant_identifier_names
    - package_prefixed_library_names
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_statements
    - directives_ordering

    # Custom rules
    - avoid_print
